# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# User specific aliases and functions
alias cd..='cd ..'

export PATH=$PATH:$HOME/bin
export PYTHONPATH=$PYTHONPATH:~/lib/python2.7/site-packages

module load boost/1.70.0-python-2.7.15
module load matplotlib/2.2.3-python-2.7.15
module load singularity
 
